### ISSUE TITLE
Murmur2Partitioner

### ISSUE THREAD

**Issue by DrNickBailey** [dpkp/kafka-python#1999]
Since upgrading to 2.0.0 I'm now getting an import error:

> --->  from kafka.partitioner import Murmur2Partitioner
> ImportError: cannot import name 'Murmur2Partitioner'

**Comment by jeffwidman** [comment]
The murmur2 partitioner has always been the default for the `KafkaConsumer`: https://github.com/dpkp/kafka-python/blob/2.0.0/kafka/partitioner/default.py

The old `SimpleConsumer` which could explicitly use the named import `Murmur2Partitioner` was removed in #1193 which was released in `2.0.0`. 

You can still import the `murmur2` function that backed both the `Murmur2Partitioner` and `KafkaConsumer`'s `DefaultPartitioner` from here: https://github.com/dpkp/kafka-python/blob/2.0.0/kafka/partitioner/__init__.py.

Depending on your use case, you may find it helpful to read the diff of #1193 for how it changed the partitioning logic imports in order to figure out whether you can just update the name or if you need to wrap it in some way if you have some very custom use case.
