### ISSUE TITLE
ssl support for python < v2.7.9 (no attribute 'SSLContext')

### ISSUE THREAD

**Issue by sragatsky** [dpkp/kafka-python#1138]
hello

Im getting the following error:

```
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    kafka_producer = SimpleKafkaProducer()
  File "/my-service/kafka_producer.py", line 28, in __init__
    self.producer = KafkaProducer(**kafka_config)
  File "./ve/lib/python2.7/site-packages/kafka/producer/kafka.py", line 266, in __init__
    client = KafkaClient(**self.config)
  File "./ve/lib/python2.7/site-packages/kafka/client_async.py", line 130, in __init__
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "./ve/lib/python2.7/site-packages/kafka/client_async.py", line 158, in _bootstrap
    bootstrap.connect()
  File "./ve/lib/python2.7/site-packages/kafka/conn.py", line 149, in connect
    self._wrap_ssl()
  File "./ve/lib/python2.7/site-packages/kafka/conn.py", line 207, in _wrap_ssl
    self._ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)  # pylint: disable=no-member
AttributeError: 'module' object has no attribute 'SSLContext'

```
I have python 2.7.3 running on (Debian 7 wheezy)
and `ssl.SSLContex` attribute was added from python v2.7.9

it seems that `kafka-python` with support for ssl connection was introduced since version 1.1.0
but it requires python version >= v2.7.9. 

Is there a way to initiate connection with ssl using lower version of python?
If not, is it possible to add support for lower version of python?

And if non of the above, please add this important fact to your documentation.

Thanks

**Comment by PeterKutschera** [comment]
Yes, please add this to the documentation! 
And also that kafka-python does not work with python3 (at least 3.2.3)- I tried because of the missing SSL in 2.7.3 .

BTW: Docu does also not specify the format of the ssl_cafile, ssl_keyfile and ssl_crlfile.

Thanks
 Peter

**Comment by dpkp** [comment]
kafka-python SSL currently relies on PEP-466 support, which was backported to python2.7 in version 2.7.9. If you can't use a recent version of python, this may be helpful:

https://pypi.python.org/pypi/backports.ssl/0.0.6

**Comment by jeffwidman** [comment]
There are warnings that are thrown on startup for the latest version of `kafka-python`, and I fixed the warnings in https://github.com/dpkp/kafka-python/pull/924/files to list the correct versions.

That said we're very open to PR's improving the docs. I'd be hesitant to merge PR's adding SSL support for lower versions of python, as I think it needlessly complicates the code given that upgrading from 2.7.3 to 2.7.9 shouldn't be that difficult at least from a code compatibility perspective...
