### ISSUE TITLE
start from 0.9.3. kafka have import error in io standard module

### ISSUE THREAD

**Issue by ZhenxingWu** [dpkp/kafka-python#468]
It seems a sily mistake, kafka's own kafka/io.py module is duplicated with python standard module. causing import error:

    from kafka import KafkaClient, SimpleProducer, KeyedProducer
  File "/usr/local/lib/python2.7/dist-packages/kafka/__init__.py", line 9, in <module>
    from kafka.client import KafkaClient
  File "/usr/local/lib/python2.7/dist-packages/kafka/client.py", line 17, in <module>
    from kafka.protocol import KafkaProtocol
  File "/usr/local/lib/python2.7/dist-packages/kafka/protocol.py", line 8, in <module>
    from kafka.codec import (
  File "/usr/local/lib/python2.7/dist-packages/kafka/codec.py", line 1, in <module>
    from io import BytesIO

it works in 0.9.2

**Comment by dpkp** [comment]
I cannot duplicate this -- can you provide more context and/or a full stacktrace?

**Comment by ZhenxingWu** [comment]
···
twu@dlsyd00032:~/Projects/ceph$ sudo pip install kafka-python==0.9.3
The directory '/home/twu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/twu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting kafka-python==0.9.3
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from kafka-python==0.9.3)
Installing collected packages: kafka-python
  Found existing installation: kafka-python 0.9.2
    Uninstalling kafka-python-0.9.2:
      Successfully uninstalled kafka-python-0.9.2
Successfully installed kafka-python-0.9.3
twu@dlsyd00032:~/Projects/ceph$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kafka/__init__.py", line 9, in <module>
    from kafka.client import KafkaClient
  File "/usr/local/lib/python2.7/dist-packages/kafka/client.py", line 17, in <module>
    from kafka.protocol import KafkaProtocol
  File "/usr/local/lib/python2.7/dist-packages/kafka/protocol.py", line 8, in <module>
    from kafka.codec import (
  File "/usr/local/lib/python2.7/dist-packages/kafka/codec.py", line 1, in <module>
    from io import BytesIO
ImportError: cannot import name BytesIO
>>> 
···

**Comment by ZhenxingWu** [comment]
it works in 0.9.2

```
$ sudo pip install kafka-python==0.9.2
Collecting kafka-python==0.9.2
Installing collected packages: kafka-python
  Found existing installation: kafka-python 0.9.3
    Uninstalling kafka-python-0.9.3:
      Successfully uninstalled kafka-python-0.9.3
Successfully installed kafka-python-0.9.2

$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaClient
>>> 
```

**Comment by dpkp** [comment]
in the broken version, can you try:
```
cd /usr/local/lib/python2.7/dist-packages/kafka/
python -c 'import io; print io.__file__'
```
and post the results?

**Comment by ZhenxingWu** [comment]
for 0.9.2

```
$ cd /usr/local/lib/python2.7/dist-packages/kafka/
$ python -c 'import io; print io.__file__'
io.pyc
```

for 0.9.3

```
$ sudo pip install kafka-python==0.9.3
Collecting kafka-python==0.9.3
Requirement already satisfied (use --upgrade to upgrade): six in
/usr/local/lib/python2.7/dist-packages (from kafka-python==0.9.3)
Installing collected packages: kafka-python
  Found existing installation: kafka-python 0.9.2
    Uninstalling kafka-python-0.9.2:
      Successfully uninstalled kafka-python-0.9.2
Successfully installed kafka-python-0.9.3
$ cd /usr/local/lib/python2.7/dist-packages/kafka/
$ python -c 'import io; print io.__file__'
io.pyc
```

Btw, if i call it in other folder:
```
$ cd -
$ python -c 'import io; print io.__file__'
/usr/lib/python2.7/io.pyc
```


On Thu, Dec 3, 2015 at 10:56 AM, Dana Powers <notifications@github.com>
wrote:

> in the broken version, can you try:
>
> cd /usr/local/lib/python2.7/dist-packages/kafka/
> python -c 'import io; print io.__file__'
>
> and post the results?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpkp/kafka-python/issues/468#issuecomment-161470993>.
>



-- 
Best Regards
Zhenxing Wu (Tim)
+86-15924181607
Your faithful friend.

**Comment by dpkp** [comment]
That's very strange. You might try simply deleting `/usr/local/lib/python2.7/dist-packages/kafka/io.pyc` . That is not part of the kafka distribution and should not be there (if I am reading your output correctly). If you figure out how that file got there and think there's something we should do to fix upstream, let me know.
