### ISSUE TITLE
KafkaConsumer.subscription() raises AttributeError when no subscription

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#1038]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./kafka_consumer.py", line 110, in run
    print consumer.subscription()
  File "/workplace/kafka-python/kafka/consumer/group.py", line 828, in subscription
    return self._subscription.subscription.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by jeffwidman** [comment]
Is there a test for an empty subscription? This was probably introduced by #1029, so I would have expected a test to catch it then.

**Comment by dpkp** [comment]
I can't reproduce this in master
