### ISSUE TITLE
seek_to_beginning is difficult to use when using topic subscription

### ISSUE THREAD

**Issue by ecksun** [dpkp/kafka-python#601]
I have some issues using `KafkaConsumer.seek_to_beginning`. The only way I have
gotten it to work thus far is to call `consumer.topics()` before calling
`seek_to_beginning`, however I do not understand why and only found it out by
trial and error.

I suggest too either update the documentation to reflect the behaviour or to
change the implementation of `seek_to_beginning` to be more intuitive. I'm more
than happy to help with the documentation however that might be of limited use
since I don't understand the current behaviour.

``` python
from kafka import KafkaConsumer

consumer = KafkaConsumer("some.topic",
                         bootstrap_servers=["kafka.example.com"],
                         group_id='some-group-id'))

# consumer.topics()
consumer.seek_to_beginning()

for message in consumer:
        print(message)
```

Without the `consumer.topics()` call I get the following exception:

```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    consumer.seek_to_beginning()
  File "./venv/lib/python3.5/site-packages/kafka/consumer/group.py", line 581, in seek_to_beginning
    assert partitions, 'No partitions are currently assigned'
AssertionError: No partitions are currently assigned

```

Im using kafka-python 1.0.2

**Comment by dpkp** [comment]
Agree, it is a bit strange. The API is modeled after the official java client, which has the same issue. I am going to wait to see how they handle it before implementing any API changes. In the meantime, you can try a few different approaches:

(1) set `auto_offset_reset='earliest'` in your KafkaConsumer configuration. This will cause the consumer to fetch from the beginning of the topic/partition if the consumer group does not have a committed offset. So this works for the first run on a consumer group, but subsequent runs will resume at whatever offset the group last committed.

(2) in addition to (1) , also set `group_id=None`. This is roughly similar to the console-consumer --from-beginning. It will not commit offsets, but it will also not do group coordination, which means you wont be able to run several consumers together and have the partitions automatically divided up and allocated between them.

(3) manually assign partitions via `consumer.assign()` instead of subscribing to topics via `consumer.subscribe()`. If you do this, `seek_to_beginning()` should work as expected.

There are a few other approaches, but these are the 3 I generally recommend at this point.

**Comment by ecksun** [comment]
Alright, thats very useful. I think those recommendations would be worth adding to the documentation.

What I want to do is to be able to restart easily during development and for that I think your second option works well.

I'm also guessing my approach is one of those few others :)

**Comment by ecksun** [comment]
I'm having a similar issue when trying to call `KafkaConsumer.assignment` on startup, it just returns an empty set. What I wan't to do is print the current offsets at startup.

**Comment by dpkp** [comment]
For topic/pattern subscriptions, partitions are assigned dynamically during poll() and iteration. They are not assigned on object creation. You might try `subscribe(topics=['foobar'], listener=rebalance_listener)` where rebalance_listener is a `kafka.consumer.subscription_state.ConsumerRebalanceListener`.

Alternatively, just call `consumer.poll()` to do an initial assignment, but beware that this also returns 'consumed' records that will be committed on the next auto-commit cycle (if you have auto-commit enabled).

**Comment by ecksun** [comment]
so whats the solution to this issue?
Should we update the documentation or just leave this issue as the documentation until the API improves?

**Comment by dpkp** [comment]
leaving open for now

**Comment by madisonb** [comment]
Using the suggested behavior above with `group_id=None` causes an exception to be thrown when the consumer is closed.

```
>>> from kafka import KafkaConsumer
>>> k = KafkaConsumer('example', bootstrap_servers=['server'], group_id=None)
>>> k.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster/lib/python2.7/site-packages/kafka/consumer/group.py", line 257, in close
    self._coordinator.close()
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster/lib/python2.7/site-packages/kafka/coordinator/consumer.py", line 306, in close
    self._maybe_auto_commit_offsets_sync()
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster/lib/python2.7/site-packages/kafka/coordinator/consumer.py", line 372, in _maybe_auto_commit_offsets_sync
    self._auto_commit_task.disable()
AttributeError: 'NoneType' object has no attribute 'disable'
>>> k = KafkaConsumer('demo.incoming', bootstrap_servers=['scdev'], group_id='stuff')
>>> k.close()
>>>
```
Would you like a new issue to fix this? This occurs regardless of whether the consumer actually consumes any messages or not.

**Comment by dpkp** [comment]
Please file a new issue thanks!

**Comment by tbsf** [comment]
I'm seeing an issue similar to this when I try seek_to_end. It seems like it isn't even trying to assign a partition. This was working in a version of 0.97. I will see if I can locate it

**Comment by rinatio** [comment]
Having same issue. Is there a link to same issue in the official API?

**Comment by tomwphillips** [comment]
I tried all three suggestions [above](https://github.com/dpkp/kafka-python/issues/601#issuecomment-197465691) and only the third, manually assigning partitions, worked for me.

```
assignments = []
for topic in topics:
    partitions = consumer.partitions_for_topic(topic)
    for p in partitions:
        assignments.append(TopicPartition(topic, p))
consumer.assign(assignments)
```

**Comment by AlJohri** [comment]
@dpkp I tried the `ConsumerRebalanceListener` suggestion above, but `consumer.assignment()` still showed an empty set. any ideas?

**Comment by seifertm** [comment]
@AlJohri Simply passing a `ConsumerRebalanceListener` to `KakfaConsumer.subscribe` is not enough. `KafkaConsumer` must have a group_id. Only then, the client will be managed by the `GroupCoordinator` and will be affected by rebalancing. This is what I ran into, at least.

**Comment by twbecker** [comment]
What's the status of this? The Java client has been well behaved in the regard for some time...

**Comment by dpkp** [comment]
I suspect it is waiting for a PR from a nice, caring person such as
yourself!

**Comment by aure-olli** [comment]
Apparently, the only thing to do is to call `consumer._client.poll()` before calling `consumer.seek_to_beginning()`. This will eventually send the metadata request, and dispatch the partitions.
```python
from kafka import KafkaConsumer
consumer = KafkaConsumer('test', bootstrap_servers='localhost:9092')
# poll has a timeout, be sure that the response has arrived
while not consumer._client.poll(): continue
consumer.seek_to_beginning()
```
That function will call `client._maybe_refresh_metadata()`,  `client._poll()` and  `client._fire_pending_completed_requests()`. There is no other function calling this sequence.

Unfortunately, the only function calling `consumer._client.poll()` are `consumer.__next__` and `consumer.poll` (which is not returning the response, so impossible to check if it has arrived), so there's no cleaner way to do this currently.

**Comment by svituz** [comment]
> Apparently, the only thing to do is to call `consumer._client.poll()` before calling `consumer.seek_to_beginning()`. This will eventually send the metadata request, and dispatch the partitions.
> 
> ```python
> from kafka import KafkaConsumer
> consumer = KafkaConsumer('test', bootstrap_servers='localhost:9092')
> # poll has a timeout, be sure that the response has arrived
> while not consumer._client.poll(): continue
> consumer.seek_to_beginning()
> ```
> 
> That function will call `client._maybe_refresh_metadata()`, `client._poll()` and `client._fire_pending_completed_requests()`. There is no other function calling this sequence.
> 
> Unfortunately, the only function calling `consumer._client.poll()` are `consumer.__next__` and `consumer.poll` (which is not returning the response, so impossible to check if it has arrived), so there's no cleaner way to do this currently.

I noticed that this works only if the consumer consumes just from one topic.
If I try to do:
```python
from kafka import KafkaConsumer
consumer = KafkaConsumer(bootstrap_servers='localhost:9092')
consumer.subscribe(['test-topic-1', 'test-topic-2])
while not consumer._client.poll(): continue
consumer.seek_to_beginning()
```
it will be stucked in the `while` loop

**Comment by jeffwidman** [comment]
IMO this is generally how Kafka async clients work, that you have to call `poll()` for the metadata to populate. I'm closing as works-as-designed, but certainly open to some documentation PR's explaining this better if anyone is interested.
