### ISSUE TITLE
SSL does not work with python 2.6

### ISSUE THREAD

**Issue by bjasmeet** [dpkp/kafka-python#931]
The conn.py seems to be using illegal code that is incompatible with python 2.6 SSL library. There is no SSLContext object in python 2.6. Failure...

AttributeError: 'module' object has no attribute 'SSLContext'

Is there a patch or a workaround

**Comment by dpkp** [comment]
No - PRs welcome though. Otherwise you'll need python 2.7+ to use SSL.

**Comment by gary02** [comment]
not  Python 2.7.9 + as #820 say? I have the same problem with Python 2.7.6  .

**Comment by bjasmeet** [comment]
Works with 2.7.13

Jasmeet

**Comment by jeffwidman** [comment]
Can this be closed? I suspect most folks will just upgrade to Python 2.7.9+ rather than try to fix this.

**Comment by dpkp** [comment]
I am ok w/ keeping it open if someone out there is really into adding python2.6 support for SSL. I'm not planning on working on it though.

**Comment by bjasmeet** [comment]
Please close
